### PR TITLE
Correction for Johansson

### PR DESCRIPTION
**Pull request by 91902078**
Dear Manuel

I added some code for Johansson setting, the result looks reasonable, please find code whether you are satisfied.

Best regards
Xiaojiang

### CODE REVIEW

**Comment by srio** [comment]
Thanks a lot Xiaojiang for this contribution. 

I add here your slide to document the changes. 

Best regards, Manuel 

image

**Comment by 91902078** [comment]
Thanks Manuel!

**Comment by srio** [comment]
You're welcome. 
The new wheels are (provisionally) here: https://silx.gitlab-pages.esrf.fr/bob/shadow3/
Please test your one (windows?). I'll do a few tests before uploading the new version to pypi.org. 

Just uninstall shadow3 and reinstall your one with the full path, for example: 
```
pip uninstall shadow3
pip install https://silx.gitlab-pages.esrf.fr/bob/shadow3/shadow3-23.4.28-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

**Comment by 91902078** [comment]
Dear Manuel

Yes, I use windows version, I test window wheel 3.8 version, shadow3-23.4.28-cp38-cp38-win_amd64.whl<https://silx.gitlab-pages.esrf.fr/bob/shadow3/shadow3-23.4.28-cp38-cp38-win_amd64.whl>, the calculation runs well, workspace and result are attached.

Thanks!
Best regards
Xiaojiang

**Pull request merged**
